- build.gradle
- src/main/java/com/wor/dash/WalkOrRunServerApplication.java
- src/main/java/com/wor/dash/config/DBConfig.java
- src/main/java/com/wor/dash/config/SwaggerConfig.java
- 커밋 컨벤션 setting -> init으로 수정
- DBConfig @MapperScan 경로 com.fitlog.war.*.model.dao -> com.wor.dash.*.model.dao로 수정 https://github.com/clapsheep/WalkOrRun-server/issues/9
> [init] 커밋 컨벤션 및 DBConfig 경로 수정

- .github/workflows/deploy.yml
1. Java 17 설정
2. Gradle로 프로젝트 빌드
3. AWS 인증
4. ECR 로그인
5. Docker 이미지 빌드 및 ECR 푸시
6. EC2에 SSH 접속해서 새 이미지로 서비스 업데이트
> [deploy] CI/CD 구축

- .github/workflows/deploy.yml
- PR에서 배포 상황을 파악하기 위한 수정
1. PR 브랜치에도 실행되도록 트리거 추가
2. Gradle 캐시 관리 추가 (빌드 속도 향상)
3. Environment와 deployment URL 설정
4.  GitHub Output 형식 업데이트 (set-output 대신>>$GITHUB_OUTPUT 사용)
5. 빌드 캐시 정리 스텝 추가
> [docs] deploy.yml 수정

- .github/workflows/deploy.yml
> [deploy] deploy.yml 수정

- .github/workflows/deploy.yml
- MySQL실행 시점과 action의 성공여부 판단 시점이 다른 문제 해결
> [docs] deploy.yml

- build.gradle
- src/main/java/com/wor/Test.java
- src/main/java/com/wor/dash/WalkOrRunServerApplication.java
- src/main/java/com/wor/dash/aop/ExecutionTimeAspect.java
- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/jwt/config/CustomLogoutHandler.java
- src/main/java/com/wor/dash/jwt/controller/AuthenticationController.java
- src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/wor/dash/jwt/model/Token.java
- src/main/java/com/wor/dash/jwt/model/dao/TokenMapper.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationService.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/service/JwtService.java
- src/main/java/com/wor/dash/jwt/model/service/JwtServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/service/TokenService.java
- src/main/java/com/wor/dash/jwt/model/service/TokenServiceImp.java
- src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
- src/main/java/com/wor/dash/response/ApiResponse.java
- src/main/java/com/wor/dash/response/AuthenticationResponse.java
- src/main/java/com/wor/dash/user/model/CustomUserDetails.java
- src/main/java/com/wor/dash/user/model/User.java
- src/main/java/com/wor/dash/user/model/dao/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserService.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/application.yml
- src/main/resources/mapper/TokenMapper.xml
- src/main/resources/mapper/UserMapper.xml
- src/test/java/com/wor/WalkOrRunServerApplicationTests.java
- 추가된 점
1. 메소드 실행시간 측정을 위한 ExecutionTimeAspect.java
2. 여러 Config 파일들
3. JWT Token 인증 시스템을 위한 jwt 및 하위 패키지들
4. User 및 하위패키지의 일부 로직 구현
5. Token, User DTO 구현
6. 응답 반환을 위한 Response 클래스 구현
7. mapper.xml
- lombok 실행 문제 및 JWT Token 인증시스템을 위한 의존성 추가 및 변경
> [feat] JWT 토큰, Spring Security 로직 구현

- src/main/resources/mapper/TokenMapper.xml
- src/main/resources/mapper/UserMapper.xml
> [refactor] mapper.xml 경로 수정

- src/main/java/com/wor/dash/aop/ExecutionTimeAspect.java
- src/main/java/com/wor/dash/jwt/model/mapper/TokenMapper.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/mapper/TokenMapper.xml
[[refactor] BugFix with JWT Token System](https://github.com/clapsheep/WalkOrRun-server/commit/1582dac78d05ceeb41d87d76bb44e650312cade4)
> [refactor] BugFix with JWT Token System

- src/main/java/com/wor/dash/comment/model/controller/CommentController.java
- src/main/java/com/wor/dash/follow/model/Follow.java
- src/main/java/com/wor/dash/follow/model/controller/FollowController.java
- src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
- src/main/java/com/wor/dash/follow/model/service/FollowService.java
- src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
- src/main/resources/mapper/CommentMapper.xml
- src/main/resources/mapper/FollowMapper.xml
- 유저 간 팔로우, 팔로우 취소, 내가 팔로우하는 유저 리스트, 나를 팔로우 하는 유저 리스트, 두 유저간 팔로우 여부에 대한 기능 구현
> [feat] Follow 기능 구현

- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/challenge/model/controller/ChallengeController.java
- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/pageInfo/model/PageInfo.java
- src/main/java/com/wor/dash/pageInfo/model/PageResponse.java
- src/main/resources/mapper/ChallengeMapper.xml
1. Challenge CRUD 기능 구현
2. 페이지네이션을 위해 PageInfo 객체 생성
3. jwt로 인해 swagger 접속 못했던 것 -> SecurityConfig에서 swagger 주소 추가
> [feat] Challnge CRUD 기능 추가

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/comment/controller/CommentController.java
- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/follow/controller/FollowController.java
- src/main/java/com/wor/dash/follow/model/Follow.java
- src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
- src/main/java/com/wor/dash/follow/model/service/FollowService.java
- src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/mapper/TokenMapper.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/password/model/PasswordAnswer.java
- src/main/java/com/wor/dash/password/model/PasswordQuestion.java
- src/main/java/com/wor/dash/password/model/mapper/PasswordMapper.java
- src/main/java/com/wor/dash/password/model/service/PasswordService.java
- src/main/java/com/wor/dash/password/model/service/PasswordServiceImpl.java
- src/main/java/com/wor/dash/record/controller/RecordController.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/java/com/wor/dash/user/model/User.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserService.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/mapper/PasswordMapper.xml
- src/main/resources/mapper/UserMapper.xml
- PasswordQuestion은 직접 입력해놔야함
- PasswordAnswer 추가, 수정 구현
- PasswordQuestion 리스트 및 검색 구현
- userId로 user가 설정해놓은 질문 및 답변 가져오는 기능 구현#41
> [feat] PasswordQnA 기능 개발

- src/main/java/com/wor/dash/WalkOrRunServerApplication.java
- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/challenge/model/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/java/com/wor/dash/record/model/Record.java
- src/main/resources/mapper/ChallengeMapper.xml
- Challenge 조회 시 진행/종료/전체 별로 조회해올 수 있도록 API 분리
- Challenge Swagger API 문서 작성
- Record에 RequireArgsConstructor 제거
> [feat] Challenge 기능 개발

- src/main/java/com/wor/dash/comment/controller/CommentController.java
- src/main/java/com/wor/dash/comment/model/Comment.java
- src/main/java/com/wor/dash/comment/model/mapper/CommentMapper.java
- src/main/java/com/wor/dash/comment/model/service/CommentService.java
- src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
- src/main/resources/mapper/CommentMapper.xml
- pageInfo 함께 담아서 리턴
- 현재 페이지, 하나 당 페이지, 전체 컨텐츠 수, 전체 페이지 수 반환
> [feat] Comment 페이지네이션 구현

- src/main/java/com/wor/dash/WalkOrRunServerApplication.java
- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/java/com/wor/dash/user/model/MyChallenge.java
- src/main/java/com/wor/dash/user/model/User.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserService.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
- 유저의 마이페이지 기능 구현
- 관리자가 유저role 변경 기능 구현
- 유저의 개인정보 수정 기능 구현
- 유저가 참여한 챌린지 리스트 가져오는 기능 구현
- 탈퇴 기능 구현
- auth 쪽에서는 탈퇴 시 unauthorize 반환 기능 구현#51
> [feat] update details of User System

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/comment/controller/CommentController.java
- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/follow/controller/FollowController.java
- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- UserController, PasswordController Swagger API 문서 추가
- 나머지 Controller들 @Tag 어노테이션 추가#44
> [docs] Swagger API 문서 추가

- src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
- src/main/java/com/wor/dash/userGoal/model/UserGoal.java
- src/main/java/com/wor/dash/userGoal/model/mapper/UserGoalMapper.java
- src/main/java/com/wor/dash/userGoal/model/service/UserGoalService.java
- src/main/java/com/wor/dash/userGoal/model/service/UserGoalServiceImpl.java
- src/main/resources/mapper/UserGoalMapper.xml
- sql쿼리문 제외하고 필요한 기능 매핑과 엔드포인트 생성
- 남은 업무 : 쿼리문 작성, 스웨거 작성, 기능 테스트 #61 #62  #
> [feat] userGoal 기능 구현

- build.gradle
- src/main/java/com/wor/dash/follow/model/Follow.java
- src/main/java/com/wor/dash/record/controller/RecordController.java
- src/main/java/com/wor/dash/record/model/Calorie.java
- src/main/java/com/wor/dash/record/model/Record.java
- src/main/java/com/wor/dash/record/model/mapper/RecordMapper.java
- src/main/java/com/wor/dash/record/model/service/RecordService.java
- src/main/java/com/wor/dash/record/model/service/RecordServiceImpl.java
- src/main/resources/mapper/RecordMapper.xml
> [feat] csv 날짜 파싱

- src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
- src/main/resources/mapper/UserGoalMapper.xml
- 스웨거 명세서 작성
- 쿼리문 거리 반환 단위 km로 통일
- 날짜 DATE에 맞게 수정
> [refactor] UserGoal API 명세서 작성

- src/main/java/com/wor/dash/comment/controller/CommentController.java
- src/main/java/com/wor/dash/comment/model/mapper/CommentMapper.java
- src/main/java/com/wor/dash/comment/model/service/CommentService.java
- src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
- src/main/java/com/wor/dash/follow/controller/FollowController.java
- src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
- src/main/java/com/wor/dash/follow/model/service/FollowService.java
- src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
- src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
- src/main/java/com/wor/dash/userGoal/model/mapper/UserGoalMapper.java
- src/main/java/com/wor/dash/userGoal/model/service/UserGoalService.java
- src/main/java/com/wor/dash/userGoal/model/service/UserGoalServiceImpl.java
- src/main/resources/mapper/CommentMapper.xml
- src/main/resources/mapper/FollowMapper.xml
- src/main/resources/mapper/UserGoalMapper.xml
- RESTful하게 API 엔드포인트 수정
- 엔드포인트에서 받는 값에 맞춰 쿼리까지 전달되는 값들 수정, 체크, API명세서 수정
> [refactor] Comment, UserGoal, Follow API 수정

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/java/com/wor/dash/comment/controller/CommentController.java
- src/main/java/com/wor/dash/config/SchedulerConfig.java
- src/main/java/com/wor/dash/follow/controller/FollowController.java
- src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
- src/main/java/com/wor/dash/util/CronUtil.java
- src/main/resources/mapper/ChallengeMapper.xml
1.  반복 주기(daily/weekly/monthly) 플래그 별로 mapper 추가
2. challengeServiceImpl 정리
> [feat] Challenge Scheduler 기능 구현

- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/java/com/wor/dash/util/CronUtil.java
- src/main/resources/mapper/ChallengeMapper.xml
1. getAllChallenges -> getAllChallengeList 같이 메서드명 변경
2. CronUtil 파일 사용안해서 삭제
> [refactor] challenge Service 메서드명 변경 (복수형 -> List) 및 사용 안하는 파일 삭제

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/java/com/wor/dash/search/controller/SearchController.java
- src/main/java/com/wor/dash/search/model/SearchService.java
- src/main/java/com/wor/dash/search/model/SearchServiceImp.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/resources/mapper/ChallengeMapper.xml
- src/main/resources/mapper/UserMapper.xml
- Challenge, Search, Comment에 페이징 기능 구현
> [feat] 페이징 기능 구현

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/resources/mapper/ChallengeMapper.xml
1. 메서드명 변경 후 다른 곳에서 변경 안해서 에러... 해결했습니다!
> [refactor] 메서드명 변경 후 에러 해결

- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserService.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
> [feat] 회원가입 시 이메일 중복확인 기능 추가

- src/main/java/com/wor/dash/password/controller/PasswordController.java
- userController, passwordController 비어있는 API 문서 작성
> [docs] swagger api문서 작성 추가

- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/resources/mapper/PasswordMapper.xml
- 개인정보 대폭 축소
- 이메일 먼저 입력해서 해당 이메일 있는지 확인 후 비밀번호 확인 질문 id 및 답변 요청 보내기
> [refactor] 비로그인 중 비밀번호 찾기 로직 수정

- src/main/resources/application.yml
- 배포 도중 "Public Key Retrieval is not allowed" 에러 발생
- MySQL 8.0 이상에서 보안 연결을 위해 필요한 설정
- application.yml SQL url에 "allowPublicKeyRetrieval=true" 추가
> [refactor] MySQL 보안방식 설정

- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- /api/auth/로 시작하는 api에 대한 권한 인증 미실시
- UserController 이메일 체크 API 엔드포인트 케밥케이스로 수정
- UserController 이메일 체크 API @PathVariable에서 @RequestParam으로 수정
> [refactor] SecurityConfig 권한 제한, 엔드포인트 및 파라미터 수정

- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/password/model/service/PasswordService.java
- src/main/java/com/wor/dash/password/model/service/PasswordServiceImpl.java
> [refactor] 비밀번호 확인 질문 리스트 출력 수정

- src/main/java/com/wor/dash/jwt/config/CustomLogoutHandler.java
- src/main/java/com/wor/dash/jwt/model/TokenSelective.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationService.java
- src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
- src/main/java/com/wor/dash/jwt/model/service/TokenService.java
- src/main/java/com/wor/dash/jwt/model/service/TokenServiceImp.java
- src/main/java/com/wor/dash/user/controller/UserController.java
- src/main/resources/mapper/TokenMapper.xml
- CustomLogoutHandler를 통한 로그아웃에서 필요한 로직만 남김
- Custom Logout API 관련 로직 삭제
> [refactor] 불필요한 코드 삭제

- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
- src/main/resources/mapper/ChallengeMapper.xml
> [refactor] SecurityConfig 파일 수정

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
- src/main/java/com/wor/dash/user/model/service/UserService.java
- src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
- src/main/resources/mapper/ChallengeMapper.xml
- 비밀번호 변경 시 userId가 필요하여 컨트롤러에서 넣는 로직 추가
- 챌린지 가져올 때 디데이도 가져오게 추가
> [refactor] 비밀번호 변경 로직 수정, 챌린지 기능 수정

- src/main/resources/mapper/ChallengeMapper.xml
- 챌린지 세부 정보 가져올 때 Comment 말고 Challenge_Participant 테이블에서 가져오게 수정
> [refactor] ChallengeMapper 수정

- src/main/resources/mapper/ChallengeMapper.xml
> [refactor] 챌린지 D-day 수정

- src/main/java/com/wor/dash/password/PasswordChangeUtil.java
- src/main/java/com/wor/dash/password/controller/PasswordController.java
- src/main/java/com/wor/dash/password/model/service/PasswordService.java
- src/main/java/com/wor/dash/password/model/service/PasswordServiceImpl.java
- src/main/resources/mapper/PasswordMapper.xml
- 마이페이지에서 비밀번호 변경 시 패스워드 질문도 변경할 수 있게 변경
> [refactor] 로그인 후 비밀번호 수정 로직 수정

- src/main/resources/mapper/ChallengeMapper.xml
> [refactor] 챌린지 매퍼 수정

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/resources/application.yml
- src/main/resources/mapper/ChallengeMapper.xml
> [refactor] 배포용 url 추가

- src/main/java/com/wor/dash/config/SecurityConfig.java
- src/main/resources/mapper/UserMapper.xml
user_role 추가
```
<select id="selectUserListForSearch" resultType="User">
select user_id, user_nickname, user_role from User
<where>
<choose>
<when test="type == 'email'">user_email like concat('%', #{value}, '%')</when>
<when test="type == 'nickname'">user_nickname like concat('%', #{value}, '%')</when>
</choose>
</where>
ORDER BY user_nickname LIMIT #{offset}, #{pageSize}
</select>
```
> [Refactor] User Mapper XML 파일 변경

- src/main/java/com/wor/dash/config/WebMvcConfiguration.java
- src/main/resources/application.yml
- 배포 사이트에서도 스웨거 접근할 수 있도록 Cors 허용
> [refactor] 스웨거 Cors 배포 사이트 허용

- src/main/java/com/wor/dash/config/SwaggerConfig.java
- src/main/java/com/wor/dash/config/WebMvcConfiguration.java
- src/main/resources/application.yml
- 배포 사이트에서도 스웨거 접근할 수 있도록 Cors 허용
> [refactor] 스웨거 Cors 배포 사이트 허용2

- src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
- src/main/java/com/wor/dash/challenge/model/Challenge.java
- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/resources/mapper/ChallengeMapper.xml
- 상세 조회에서 참여중인 유저 정보 반환되게 수정
- 불필요한 파라미터 제거
> [refactor] Challenge 상세조회 데이터 수정 

- src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
- src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
- src/main/resources/mapper/ChallengeMapper.xml
> [refactor] 기능 수정
